### ISSUE TITLE
Invalid sorting for Contribution results when top contributors are negative (Absolute values)

### ISSUE THREAD

**Issue by nabilahmed739** [brightway-lca/brightway2-analyzer#18]
When getting the contribution results, if the top contributions have a negative value BW analyzer ignore these. The issue is in the limit calculation, as it doesnt take negatives into account. 

I have tried the following fix and it works:
[contribution.py > ContributionAnalysis > sort_array() method > line 44](https://github.com/brightway-lca/brightway2-analyzer/blob/master/bw2analyzer/contribution.py#L44)
Currently: `limit = (data >= (total * limit)).sum()`
Fix: `limit = (np.abs(data) >= (total * limit)).sum()`

Does this issue have any horizontal impacts? (Other places where negatives may not have been considered?)

**Comment by cmutel** [comment]
Fix in 0.11.2, with works on both bw2 and bw2.5, and released on pypi and anaconda.org on 2022-04-01.
