### ISSUE TITLE
Appdirs causing CI error on Ubuntu py2.7

### ISSUE THREAD

**Issue by cmutel** [brightway-lca/brightway2-analyzer#5]
See [CI error log](https://dev.azure.com/mutel/Brightway%20CI/_build/results?buildId=9&view=logs&j=1b95ab4c-10f8-5fbd-58dd-76a922c71ebf&t=9131e487-7b03-51ac-d427-6e3d3c9a7d86).

Sounds like fun...

**Comment by tngTUDOR** [comment]
@cmutel if bw2 won't support py2.7 anymore, this issue could be closed "won't fix"

**Comment by cmutel** [comment]
@tngTUDOR We don't test against 2.7, and strongly discourage people from using it. But Brightway2 should be 2.7 compatible - is this an issue you are seeing in production, or just browsing old issues on a Saturday night?

**Comment by tngTUDOR** [comment]
Just browsing 😉
